version: "3.9"

services:

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - doctor-service
      - billing-service
      - appointment-service


  user-service:
    build:
      context: ./apis/user-services
    container_name: user-service
    ports:
      - "3001:3001"

  doctor-service:
    build:
      context: ./apis/doctor-services
    container_name: doctor-service
    ports:
      - "3002:3002"

  billing-service:
    build:
      context: ./apis/billing-service
    container_name: billing-service
    ports:
      - "3003:3003"

  appointment-service:
    build:
      context: ./apis/appointment-service
    container_name: appointment-service
    ports:
      - "3004:3004"

  